### PR TITLE
Fix grunt dependencies for npm 2.0.0

### PR DESCRIPTION
**Pull request by brittanydionigi**
This should resolve the install issue opened at mozilla/recroom#41 Though there are still significant issues with npm 2.0.0 that are being worked out. (https://github.com/npm/npm/issues/6043 / https://twitter.com/othiym23/status/507042794997682176)

Everything should still work as expected when using with npm 1.4.26 but would like somebody else to test out as well.

### CODE REVIEW

**Comment by brittanydionigi** [comment]
Also, this just in:

**othiym23>** brittanstoroz: we may or may not revert the change (npm/npm@ea547e29f1245e516fc67641875841c10f04e1ee) before the final release of 2.0.0, depending on how that thread (mojombo/semver#221) plays out

So maybe let's wait on this.

**Comment by fwenzel** [comment]
Looks like you're mostly upgrading dependencies, right? Is it going to re-break if they back out that change? If so, let's wait. If not, then we'd probably be fine landing this anyway. (But I'll leave it to @tofumatt to make that call)

**Comment by brittanydionigi** [comment]
Right - It shouldn't re-break if they back out of the change - I tested it out in 1.4 and everything worked as usual.  But yes, would like to see if @tofumatt knows of anything off the bat that might make this problematic.

**Comment by vladikoff** [comment]
We saw this issue a few days ago, the only dependency that you need to update is `grunt-contrib-uglify`, see this PR https://github.com/mozilla/generator-recroom/pull/19

**Comment by brittanydionigi** [comment]
Closing this in favor of @vladikoff's simpler solution which also resolves the issue.

**Pull request closed without merging**
